name = "nostru-web"
main = "src/index.ts"
compatibility_date = "2026-06-20"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

routes = [
  { pattern = "nostru.net/*", zone_name = "nostru.net" },
  { pattern = "www.nostru.net/*", zone_name = "nostru.net" },
]

[[kv_namespaces]]
binding = "NIP05"
id = "8e4b837c5141436ba013a341f41498ed"
preview_id = "3f83a95b2a444c34b63966c497d5cadb"
